```{r}
link = 'https://raw.githubusercontent.com/Group-6-542/EmilyRepository/50e2502dfe3fde3a633f8ca193eb0c6ff76aafe5/mergedGroupDataFinal.csv'
myfile = url(link)
fromPy = read.csv(file = myfile)

# reset indexes to R format:
row.names(fromPy)=NULL
```
```{r}
#verify data structure
str(fromPy,width = 50,strict.width='cut')

```
```{r}
#prepare hypotheses
# hypothesis 1: culturalSpaces increases as avgAGI increases:
hypo1=formula(culturalSpaces~ avgAGI)

# hypothesis 2: casesReported decreases as avgAGI increases:

hypo2=formula(casesReported~ avgAGI)
```
```{r}
#
# results
gauss1=glm(hypo1,
           data = fromPy,
           family = 'gaussian')

gauss2=glm(hypo2,
           data = fromPy,
           family = 'gaussian')
```

```{r}
summary(gauss1)
```
```{r}
summary(gauss2)
```

```{r}
install.packages("rsq")
```
```{r}
library(rsq)
rsq(gauss2,adj=T)
```

```{r}
library(rsq)
rsq(gauss1,adj=T)
```

```{r}
# hypo 3 - numberOfPets increases as numberOfReturns increases
hypo3=formula(numberOfPets~ numberOfReturns)
```

```{r}
gauss3=glm(hypo3,
           data = fromPy,
           family = 'gaussian')
```

```{r}
summary(gauss3)
```

```{r}
library(rsq)
rsq(gauss3,adj=T)
```

```{r}
# hypo 4 - numberOfPets increases as avgAGI increases
hypo4=formula(numberOfPets~ avgAGI)
```

```{r}
gauss4=glm(hypo4,
           data = fromPy,
           family = 'gaussian')
```

```{r}
summary(gauss4)
```
```{r}
library(rsq)
rsq(gauss4,adj=T)
```

```{r}
anova(gauss3,gauss4,test="Chisq")
```

```{r}
install.packages("dotwhisker")
```

```{r}
library(dotwhisker)
```

```{r}
dwplot(gauss3,by_2sd = F)
```
```{r}
library("margins")
cplot(gauss3,"numberOfReturns")
```
```{r}
#Binary outcome

fromPy$numberOfReturnsdico=ifelse(fromPy$numberOfReturns>median(fromPy$numberOfReturns,
                                        na.rm = T),
                      1,0)
```

```{r}
hypoDico1=formula(numberOfReturnsdico~ numberOfPets)
```

```{r}
fromPy$numberOfReturnsdico=factor(fromPy$numberOfReturnsdico)
```

```{r}
Logi1=glm(hypoDico1,data = fromPy,
          family = "binomial")
```

```{r}
summary(Logi1)
```

```{r}
library(margins)
(marginsINFO = margins(Logi1))
```

```{r}
(marginsSUMM=summary(marginsINFO))
```

```{r}
fromPy$numberOfPetsdico=ifelse(fromPy$numberOfPets>median(fromPy$numberOfPets,
                                        na.rm = T),
                      1,0)
```

```{r}
hypoDico2=formula(numberOfPetsdico~ numberOfReturns * culturalSpaces)
```

```{r}
Logi2=glm(hypoDico2,data = fromPy,
          family = "binomial")
```

```{r}
summary(Logi2)
```

```{r}
library("lmtest")
lmtest::lrtest(Logi1,Logi2)
```

```{r}

fromPy$numberOfPetsdico=ifelse(fromPy$numberOfPets>median(fromPy$numberOfPets,
                                        na.rm = T),
                      1,0)
```

```{r}
hypoDico3=formula(numberOfPetsdico~ numberOfReturns)
```

```{r}
Logi3=glm(hypoDico3,data = fromPy,
          family = "binomial")
```

```{r}
lmtest::lrtest(Logi2,Logi3)
```

```{r}
hypoDico4=formula(numberOfPetsdico~ numberOfReturns * avgAGI)
```

```{r}
Logi4=glm(hypoDico4,data = fromPy,
          family = "binomial")
```

```{r}
summary(Logi4)
```

```{r}
lmtest::lrtest(Logi2,Logi4)
```

```{r}
#logi4 is the better model

library(margins)
(marginsINFO = margins(Logi4))
```

```{r}
(marginsSUMM=summary(marginsINFO))
```

```{r}
base= ggplot(marginsSUMM,
             aes(x=factor, y=AME))
base= base + geom_point()

plotMargins = base + theme(axis.text.x = element_text(angle = 80,size = 6,hjust = 1))
plotMargins    
```
```{r}
plotMargins +  geom_errorbar(aes(ymin=lower,
                                 ymax=upper))
```

```{r}
cplot(Logi4, "avgAGI")
```

```{r}
cplot(Logi4, "numberOfReturns")
```

```{r}
persp(Logi4)
```

